<a href="https://colab.research.google.com/github/thxxx/datascience/blob/main/hospital.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
path = '/content/drive/MyDrive/data/dacon/'
os.listdir(path) # path에 뭐가 들어있는지 보여준다.

['submission_sample.csv', 'test.csv', 'train.csv']

In [ ]:
tdf = pd.read_csv(os.path.join(path + 'train.csv'), encoding='utf-8')
test_df = pd.read_csv(os.path.join(path + 'test.csv'), encoding='utf-8')
sdf = pd.read_csv(os.path.join(path + 'submission_sample.csv'), encoding='utf-8')

In [ ]:
tdf.head(10)

inst_id    OC       sido  ...  employee1  employee2  ownerChange
0        1  open  choongnam  ...       62.0       64.0         same
1        3  open  gyeongnam  ...      801.0      813.0         same
2        4  open   gyeonggi  ...      234.0        1.0         same
3        7  open    incheon  ...      663.0      663.0         same
4        9  open  gyeongnam  ...      206.0      197.0         same
5       11  open  gyeongnam  ...      397.0      390.0         same
6       14  open   gyeonggi  ...      221.0      246.0         same
7       15  open      busan  ...      489.0      489.0         same
8       16  open    jeonnam  ...      243.0      243.0         same
9       17  open      seoul  ...      370.0      382.0         same

[10 rows x 58 columns]

In [ ]:
tdf[(tdf['bedCount']<300)].isna()

inst_id     OC   sido    sgg  ...  surplus2  employee1  employee2  ownerChange
0      False  False  False  False  ...     False      False      False        False
4      False  False  False  False  ...     False      False      False        False
5      False  False  False  False  ...     False      False      False        False
6      False  False  False  False  ...     False      False      False        False
7      False  False  False  False  ...     False      False      False        False
..       ...    ...    ...    ...  ...       ...        ...        ...          ...
291    False  False  False  False  ...     False      False      False        False
293    False  False  False  False  ...     False      False      False        False
295    False  False  False  False  ...     False      False      False        False
296    False  False  False  False  ...     False      False      False        False
299    False  False  False  False  ...     False      False       True         True

[271 rows x 58 columns]

In [ ]:
tdf.head()

inst_id    OC       sido  ...  employee1  employee2  ownerChange
0        1  open  choongnam  ...       62.0       64.0         same
1        3  open  gyeongnam  ...      801.0      813.0         same
2        4  open   gyeonggi  ...      234.0        1.0         same
3        7  open    incheon  ...      663.0      663.0         same
4        9  open  gyeongnam  ...      206.0      197.0         same

[5 rows x 58 columns]

In [ ]:
tdf['OC'] = tdf['OC'].apply(lambda x: 0 if x=='open' else 1)

In [ ]:
print(f"전체 병원 수 :{tdf['OC'].count()}, 폐업한 병원 수 : {sum(tdf['OC']==1)}")

전체 병원 수 :301, 폐업한 병원 수 : 15


In [ ]:
tdf.describe()

inst_id          OC  ...    employee1    employee2
count  301.000000  301.000000  ...   291.000000   288.000000
mean   219.056478    0.049834  ...   142.546392   134.326389
std    121.234869    0.217964  ...   160.191073   151.061786
min      1.000000    0.000000  ...     0.000000     0.000000
25%    112.000000    0.000000  ...    53.500000    53.750000
50%    230.000000    0.000000  ...    80.000000    79.000000
75%    321.000000    0.000000  ...   181.500000   170.000000
max    428.000000    1.000000  ...  1200.000000  1200.000000

[8 rows x 55 columns]

In [ ]:
print(sum(tdf['revenue1']>0), sum(tdf['salary1']>0), sum(tdf['noi1']>0))

289 282 285


In [ ]:
tdf.sort_values(by=['bedCount'], inplace=False, ascending=False)
print(tdf.iloc[3:10, 0:5].head())

   inst_id  OC       sido  sgg  openDate
3        7   0    incheon  141  20000814
4        9   0  gyeongnam   32  20050901
5       11   0  gyeongnam  155  20020501
6       14   0   gyeonggi  169  19820702
7       15   0      busan   66  19871102


In [ ]:
tdfgroup = tdf.groupby(by='sgg')
tdfgroup.head()

inst_id  OC       sido  ...  employee1  employee2  ownerChange
0          1   0  choongnam  ...       62.0       64.0         same
1          3   0  gyeongnam  ...      801.0      813.0         same
2          4   0   gyeonggi  ...      234.0        1.0         same
3          7   0    incheon  ...      663.0      663.0         same
4          9   0  gyeongnam  ...      206.0      197.0         same
..       ...  ..        ...  ...        ...        ...          ...
295      420   0   gyeonggi  ...       62.0       66.0         same
296      422   0    jeonnam  ...      193.0      141.0         same
297      423   1  choongnam  ...       79.0       79.0         same
298      426   1  gyeongbuk  ...        NaN        NaN          NaN
300      428   0      seoul  ...       15.0       15.0         same

[289 rows x 58 columns]

In [ ]:
tdf['profit1'] = tdf['profit1'].fillna('0')
print(tdf['profit1'])

0       2.2517e+08
1                0
2      4.18648e+07
3       9.0283e+08
4      8.07497e+07
          ...     
296    5.94387e+08
297   -1.62252e+09
298   -7.17531e+07
299   -1.85055e+09
300   -4.55093e+07
Name: profit1, Length: 301, dtype: object


In [ ]:
(sdf['OC'] == 1).sum()

0

In [ ]:
from sklearn.model_selection import StratifiedKFold
skfold = StratifiedKFold(n_splits=3)
n_iter = 0

In [ ]:
tdf['ownerChange'] = tdf['ownerChange'].fillna('same')
tdf['ownerChange']

0      same
1      same
2      same
3      same
4      same
       ... 
296    same
297    same
298    same
299    same
300    same
Name: ownerChange, Length: 301, dtype: object

In [ ]:
tdf['ownerChange'] = tdf['ownerChange'].apply(lambda x: 0 if x=='same' else 1 )

In [ ]:
tdf['OC'].value_counts()

0    286
1     15
Name: OC, dtype: int64

In [ ]:
tdf['instkind'].value_counts()

nursing_hospital        144
hospital                 88
general_hospital         37
clinic                   18
traditional_hospital      8
traditional_clinic        4
dental_clinic             1
Name: instkind, dtype: int64

In [ ]:
tdf['sido'].value_counts()

gyeonggi     49
gyeongbuk    39
gyeongnam    35
busan        26
choongnam    23
jeonnam      21
seoul        19
jeonbuk      18
daegu        14
choongbuk    13
daejeon      13
gangwon      10
incheon      10
ulsan         8
gwangju       2
sejong        1
Name: sido, dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

items = ['gyeonggi', 'gyeongbuk', 'gyeongnam', 'busan', 'choongnam','jeonnam','seoul','jeonbuk','daegu','daejeon','choongbuk','gangwon',
         'incheon','ulsan','sejong', 'gwangju']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print(f"인코딩 최종 변환 값 : {labels}")
print(f"인코딩 클래스 : {encoder.classes_}")

인코딩 최종 변환 값 : [ 8  7  9  0  2 12 14 11  3  4  1  5 10 15 13  6]
인코딩 클래스 : ['busan' 'choongbuk' 'choongnam' 'daegu' 'daejeon' 'gangwon' 'gwangju'
 'gyeongbuk' 'gyeonggi' 'gyeongnam' 'incheon' 'jeonbuk' 'jeonnam' 'sejong'
 'seoul' 'ulsan']


In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

items = ['gyeonggi', 'gyeongbuk', 'gyeongnam', 'busan', 'choongnam','jeonnam','seoul','jeonbuk','daegu','daejeon','choongbuk','gangwon',
         'incheon','ulsan','sejong', 'gwangju']

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

labels = labels.reshape(-1,1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
print('원핫 인코딩 데이터 \n', oh_labels.toarray())

원핫 인코딩 데이터 
 [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
tdf.head()

inst_id  OC       sido  sgg  ...      surplus2  employee1 employee2  ownerChange
0        1   0  choongnam   73  ...  1.271224e+09       62.0      64.0            0
1        3   0  gyeongnam   32  ...           NaN      801.0     813.0            0
2        4   0   gyeonggi   89  ...  0.000000e+00      234.0       1.0            0
3        7   0    incheon  141  ...  7.740829e+09      663.0     663.0            0
4        9   0  gyeongnam   32  ...  9.025550e+09      206.0     197.0            0

[5 rows x 58 columns]

In [ ]:
tdf.drop(['instkind', 'sido'], axis=1, inplace=True)
# print(tdf.drop([1], axis=0, inplace=True))


In [ ]:
print(sum(tdf['revenue1'].isna()),sum(tdf['salary1'].isna()),sum(tdf['noe1'].isna()))

8 8 8


In [ ]:
tdf.index

RangeIndex(start=0, stop=301, step=1)

In [ ]:
# for x in tdf.index:
#   print(x)

for i, x in enumerate(list(tdf['revenue1'].isna())):
  if x == True:
    print(tdf.drop(i, axis=0, inplace=True))



None
None
None
None
None
None
None
None


In [ ]:
print(sum(tdf['revenue1'].isna()),sum(tdf['salary1'].isna()),sum(tdf['noe1'].isna()))

0 0 0


In [ ]:
tdf.columns

Index(['inst_id', 'OC', 'sgg', 'openDate', 'bedCount', 'revenue1',
       'salescost1', 'sga1', 'salary1', 'noi1', 'noe1', 'interest1', 'ctax1',
       'profit1', 'liquidAsset1', 'quickAsset1', 'receivableS1',
       'inventoryAsset1', 'nonCAsset1', 'tanAsset1', 'OnonCAsset1',
       'receivableL1', 'debt1', 'liquidLiabilities1', 'shortLoan1',
       'NCLiabilities1', 'longLoan1', 'netAsset1', 'surplus1', 'revenue2',
       'salescost2', 'sga2', 'salary2', 'noi2', 'noe2', 'interest2', 'ctax2',
       'profit2', 'liquidAsset2', 'quickAsset2', 'receivableS2',
       'inventoryAsset2', 'nonCAsset2', 'tanAsset2', 'OnonCAsset2',
       'receivableL2', 'debt2', 'liquidLiabilities2', 'shortLoan2',
       'NCLiabilities2', 'longLoan2', 'netAsset2', 'surplus2', 'employee1',
       'employee2', 'ownerChange'],
      dtype='object')

In [ ]:
tdf.values

array([[1, 0, 73, ..., 62.0, 64.0, 0],
       [4, 0, 89, ..., 234.0, 1.0, 0],
       [7, 0, 141, ..., 663.0, 663.0, 0],
       ...,
       [426, 1, 107, ..., nan, nan, 0],
       [427, 1, 169, ..., 100.0, nan, 0],
       [428, 0, 79, ..., 15.0, 15.0, 0]], dtype=object)

In [ ]:
tdf['bedCount'] = tdf['bedCount'].fillna(tdf['bedCount'].mean())

In [ ]:
tdf['employee1'] = tdf['employee1'].fillna(tdf['employee1'].mean())
tdf['employee2'] = tdf['employee2'].fillna(tdf['employee2'].mean())

In [ ]:
tdf.head()

inst_id  OC  sgg  openDate  ...      surplus2  employee1  employee2  ownerChange
0        1   0   73  20071228  ...  1.271224e+09       62.0       64.0            0
2        4   0   89  20161228  ...  0.000000e+00      234.0        1.0            0
3        7   0  141  20000814  ...  7.740829e+09      663.0      663.0            0
4        9   0   32  20050901  ...  9.025550e+09      206.0      197.0            0
5       11   0  155  20020501  ...  5.879004e+09      397.0      390.0            0

[5 rows x 56 columns]

In [ ]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 293 entries, 0 to 300
Data columns (total 56 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   inst_id             293 non-null    int64  
 1   OC                  293 non-null    int64  
 2   sgg                 293 non-null    int64  
 3   openDate            293 non-null    int64  
 4   bedCount            293 non-null    float64
 5   revenue1            293 non-null    float64
 6   salescost1          293 non-null    float64
 7   sga1                293 non-null    float64
 8   salary1             293 non-null    float64
 9   noi1                293 non-null    float64
 10  noe1                293 non-null    float64
 11  interest1           293 non-null    float64
 12  ctax1               293 non-null    float64
 13  profit1             293 non-null    object 
 14  liquidAsset1        293 non-null    float64
 15  quickAsset1         293 non-null    float64
 16  receivab

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=5)
n_iter = 0

train_label = tdf['OC']

tdf = tdf.drop(['OC'], axis=1)
# 학습데이터 세트로만 학습하고 예측했을 때! 정확도는 100%가 나온다.

# train_data = tdf.values
# train_label = tdf['OC']
# dt_clf.fit(train_data, train_label)

# pred = dt_clf.predict(train_data)
# print("정확도 : ",accuracy_score(train_label, pred))

In [ ]:
dt_clf = DecisionTreeClassifier()
import numpy as np
cv_accuracy = []

In [ ]:
# for train_index, test_index in skf.split(tdf, train_label):
#   X_train, X_test = tdf.iloc[train_index], tdf.iloc[test_index]
#   y_train, y_test = train_label.iloc[train_index], train_label.iloc[train_index]
#   dt_clf.fit(X_train, y_train)
#   pred = dt_clf.predict(X_test)

#   #반복시마다 정확도 측정
#   n_iter += 1
#   acc = (accuracy_score(y_test, pred))
#   train_size = X_train.shape[0]
#   test_size = X_test.shape[0]
#   print(f"교차 검증 정확도 : {acc}, 학습 데이터 크기 : {train_size}, 검증 데이터 크기 : {test_size}")
#   print(f"#{n_iter}검증 세트 인덱스 : {test_index}")
#   cv_accuracy.append(acc)

# print(f"교차 검증별 정확도 : {np.round(cv_accuracy), 4}")
# print(f"평균 검증 정확도 : {np.mean(cv_accuracy)}")

ValueError: ignored

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(tdf.values, train_label, test_size=0.3, random_state=177)

In [ ]:
pred = np.zeros(293, dtype="int64")
print("정확도 : ",accuracy_score(y_test, pred))

ValueError: ignored

In [ ]:
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)

In [ ]:
print(pred)
print(y_test)

[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
192    0
293    0
183    0
179    0
296    0
      ..
35     1
59     0
120    0
20     0
10     0
Name: OC, Length: 88, dtype: int64


In [ ]:
print("정확도 : ",accuracy_score(y_test, pred))

정확도 :  0.9204545454545454


In [ ]:
print(tdf['sido'].value_counts())
print(tdf['sido'].count())

KeyError: ignored

In [ ]:
tdf[tdf['OC'] != 0]

In [ ]:
tdf