<a href="https://colab.research.google.com/github/thxxx/datascience/blob/master/types.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import requests
from bs4 import BeautifulSoup


In [ ]:
result_store = requests.get("https://play.google.com/store/apps")
result_store.raise_for_status
# store_health = requests.get("https://play.google.com/store/apps/category/HEALTH_AND_FITNESS")
print(result_store)

store_soup = BeautifulSoup(result_store.text, "html.parser")
# health_soup = BeautifulSoup(store_health.text, "html.parser")

pagination = store_soup.find_all("div", {"class": "W9yFB"})

print(len(result_store.text))

<Response [200]>
1018985


In [6]:
!python --version

Python 3.7.10


In [8]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [11]:
a = [1,2,3]
b = ['a', 'b', 'c']
c = [["a"], ["a", "b"], ["a", "b", "c"]]
print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'b', 'c']]


In [12]:
c.append('new')
c.append(['new list'])
print(c)

[['a'], ['a', 'b'], ['a', 'b', 'c'], 'new', ['new list']]


In [13]:
a = np.array(["a", "b"])
print(a)
print(type(a))

['a' 'b']
<class 'numpy.ndarray'>


In [15]:
print(np.arange(10))
print(np.arange(3,9,2))

[0 1 2 3 4 5 6 7 8 9]
[3 5 7]


In [17]:
mat2 = np.random.randint(low=1, high=10, size=(3,2))
print(mat2)

[[5 8]
 [1 7]
 [6 3]]


In [19]:
mat1 = np.ones((3,6), dtype='int')
print(mat1)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


In [21]:
mat1 = mat1.reshape(-1,2)
print(mat1)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [22]:
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

print(z1.shape, z2.shape)

(1, 3) (1, 2)


In [23]:
xx = np.random.rand(15)
print(xx)
print(xx.argsort()) # 정렬되어야하는 인덱스 순서를 알려줌

[0.08419429 0.29558735 0.22297315 0.12497837 0.65894732 0.77186793
 0.78344706 0.45494067 0.89958793 0.9124788  0.68614922 0.95368801
 0.91548106 0.35707283 0.44888077]
[ 0  3  2  1 13 14  7  4 10  5  6  8  9 12 11]


In [24]:
import pandas as pd

시리즈는 1차원 데이터 집합,
데이터프레임은 2차원 데이터 집합.
행렬과 같이 row 와 column으로 이루어져 있음.

In [25]:
pd_series = pd.Series(index = ['a','b','c','d'], data=[1,2,3,4])
pd_series

a    1
b    2
c    3
d    4
dtype: int64

In [26]:
print(pd_series.ndim)

1


In [28]:
# iloc, loc 주요함!
print(pd_series.loc['a'])
print(pd_series.iloc[2])

1
3


In [30]:
pd_series.drop('b')

a    1
c    3
d    4
dtype: int64

In [33]:
print(pd_series) # 다시 b가 부활
pd_series.drop('b', inplace=True)
print(pd_series) # 완전히 죽음

a    1
c    3
d    4
dtype: int64


KeyError: ignored

In [35]:
data = {
    'A':np.arange(15),
    'B':np.random.randint(low=0,high=15,size=(15)),
    'C':np.random.rand(15)
}

data_df = pd.DataFrame(data)

In [36]:
data_df.head()

A  B         C
0  0  8  0.877211
1  1  2  0.182880
2  2  7  0.701448
3  3  1  0.451454
4  4  2  0.935319

In [37]:
data_df.tail()

A   B         C
10  10   2  0.807839
11  11  10  0.931536
12  12   8  0.898748
13  13  12  0.389876
14  14   5  0.444751

In [38]:
data_df[1:3] # 1 ~ 3전까지 1,2

A  B         C
1  1  2  0.182880
2  2  7  0.701448

In [40]:
data_df.loc[1]['C']

0.18287973500690147

In [41]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0   8  0.877211  False
1    1   2  0.182880  False
2    2   7  0.701448  False
3    3   1  0.451454  False
4    4   2  0.935319  False
5    5  12  0.819001   True
6    6   5  0.374130   True
7    7   8  0.836207   True
8    8   8  0.127762   True
9    9   6  0.769581   True
10  10   2  0.807839   True
11  11  10  0.931536   True
12  12   8  0.898748   True
13  13  12  0.389876   True
14  14   5  0.444751   True

In [42]:
data_df.drop('D', axis=1, inplace=True)
data_df.head()

A  B         C
0  0  8  0.877211
1  1  2  0.182880
2  2  7  0.701448
3  3  1  0.451454
4  4  2  0.935319

In [43]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14   5  0.444751
13  13  12  0.389876
12  12   8  0.898748
11  11  10  0.931536
10  10   2  0.807839
9    9   6  0.769581
8    8   8  0.127762
7    7   8  0.836207
6    6   5  0.374130
5    5  12  0.819001
4    4   2  0.935319
3    3   1  0.451454
2    2   7  0.701448
1    1   2  0.182880
0    0   8  0.877211

In [44]:
import torch

In [46]:
# tensor란? multi dimensional array.
v_data = [1.,2.,3.]
v = torch.Tensor(v_data)
print(v)

tensor([1., 2., 3.])


In [48]:
rand_points = torch.rand((2,3), dtype=torch.float)
print(rand_points)

tensor([[0.6157, 0.9944, 0.0801],
        [0.2008, 0.9414, 0.0294]])


In [49]:
print(rand_points.dtype)

torch.float32


In [50]:
print(rand_points.size())

torch.Size([2, 3])


In [53]:
y = rand_points.view(-1,6)
print(y)

tensor([[0.6157, 0.9944, 0.0801, 0.2008, 0.9414, 0.0294]])


In [56]:
# 더하기의 방법 총 4개
#1 
y = torch.ones(3,2)
x = torch.ones(1,2)
print(x)
print(y)
print(torch.add(x,y)) # 각각에 더해줌

tensor([[1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])


In [60]:
p = torch.ones(3,4)
pn = p.numpy()
print(p)
print(type(pn))
ps = torch.from_numpy(pn)
print(type(ps))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
<class 'numpy.ndarray'>
<class 'torch.Tensor'>
