In [9]:
import numpy as np
arr1 = np.arange(10)
print(arr1)
arr2 = arr1.reshape(2,5)
print(arr2)
arr3 = arr2.reshape(-1,1)
print(arr3.tolist(), arr3.shape)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9]] (10, 1)


In [13]:
arr1 = np.arange(start=1, stop=10)
print(arr1[4], type(arr1[4]))

5 <class 'numpy.int64'>


In [34]:
arr4 = arr1.reshape(3,3)
print(arr4)
print(arr4[0:3, 2], arr4[0:3, 2].shape)
arr5 = np.arange(1,10)
print(arr5.reshape(-1,1)[0:3], arr5.reshape(-1,1)[0:3].shape)
print(arr4[arr4>5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[3 6 9] (3,)
[[1]
 [2]
 [3]] (3, 1)
[6 7 8 9]


In [40]:
arr3 = np.array([[12,8],[7,1]])
print(arr3)
print(np.sort(arr3, axis=0))
print(np.sort(arr3, axis=1))

[[12  8]
 [ 7  1]]
[[ 7  1]
 [12  8]]
[[ 8 12]
 [ 1  7]]
